account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

articles/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'articles'

urlpatterns = [
    path(
        'articles',
        views.ArticleList.as_view(),
        name='article_list'
    ),

    path(
        'articles/page/<int:page>',
        views.ArticleList.as_view(),
        name='article_list'
    ),

    path(
        'article/<int:pk>',
        views.ArticleDetail.as_view(),
        name='article_detail'
    ),

    # path(
    #     'article/created/',
    #     login_required(views.ArticleCreated.as_view(), login_url='/account/login'),
    #     name='article_created'
    # ),

    path(
        '',
        views.ArticleList.as_view(),
        name='articles_list'
    ),

    path(
        'page/<int:page>',
        views.ArticleList.as_view(),
        name='articles_list'
    ),
]

blog_with_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('articles.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
      <meta name="description" content="">
      <meta name="author" content="">
      {% block meta %} {% endblock %}
      <link rel="icon" href="#">

      <title>{% block head_title %}Blog Template for Bootstrap{% endblock %}</title>

      <!-- Bootstrap core CSS -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

      <!-- Custom styles for this template -->
      <link href="{% static 'base/css/base.css' %}" rel="stylesheet">


      {% block link %} {% endblock %}


  </head>


  <body>

      <!--导航栏内容-->
      {% include 'nav.html' %}



      <!--主要内容-->
      {% block container %}
        <div class="container">
        </div><!-- /.container -->
      {% endblock %}



      <!--底部内容-->
      {% block footer %}
      <!--{% include 'footer.html' %}-->
      {% endblock %}


      <!-- JS, Popper.js, and jQuery -->
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

  {% block script %}{% endblock %}

  </body>
</html>

templates/footer.html
<footer class="footer">
    <div class="container">
        <p class="center"></p>
    </div>
</footer>

templates/nav.html
{% load account_tags %}
<nav class="navbar navbar-expand-md navbar-light">
    <div class="container">
        <a href="{% url 'articles:article_list' %}" class="navbar-brand">Blog</a>
            <div class="d-flex ml-auto">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#globalNavbar" aria-controls="globalNavbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            </div>
            <div class="collapse navbar-collapse" id="globalNavbar">
                <form class="form-inline form-navbar my-2 my-lg-0 order-2" action="{% url 'articles:articles_list' %}">
                    <input class="form-control" name="s" type="text" placeholder="{% if s %}{{ s }}{% else %}搜索{% endif %}"/>
                </form>
                <ul class="navbar-nav mr-auto order-1">
                    <li class="nav-item"><a class="nav-link" href="{% url 'articles:article_list' %}">博客列表</a></li>
                    <li class="nav-item"><a class="nav-link" href="#">新建博客</a></li>
                </ul>
                <ul class="navbar-nav d-none d-md-flex ml-2 order-3">
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account:profile' %}"><img class="img-rounded profile-thumbnail pull-left" style="margin: 0 2px 0 0" src="{{ user|gravatar:'20' }}">{{ user.username }}</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account:logout' %}">登出</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account:login' %}">登录</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account:register' %}">注册</a></li>
                    {% endif %}
                </ul>
                <!--<ul class="navbar-nav d-lg-none">-->
                  <!--<li class="nav-item-divider"></li>-->
                  <!--<li class="nav-item"><a class="nav-link" href="{% url 'account:login' %}">Sign in</a></li>-->
                  <!--<li class="nav-item"><a class="nav-link" href="{% url 'account:register' %}">Sign up</a></li>-->
                <!--</ul>-->
            </div>
    </div>
</nav>