account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

blog_with_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('articles.urls')),
]

comments/urls.py
from django.urls import path
from . import views


app_name = 'comments'

urlpatterns = [
    path('post-comment/<int:article_id>/', views.CommentPostView.as_view(), name='post_comment'),
    path(
        'post-comment/<int:article_id>/<int:parent_comment_id>',
        views.CommentPostView.as_view(),
        name='comment_reply'
    ),
]

comments/models.py
from django.db import models
from django.conf import settings
from articles.models import Article
from django.utils.timezone import now
from ckeditor.fields import RichTextField


class Comment(models.Model):
    body = RichTextField()
    create_time = models.DateTimeField('创建时间', default=now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE)
    article = models.ForeignKey(Article, verbose_name='文章', on_delete=models.CASCADE)
    parent_comment = models.ForeignKey(
        'self',
        verbose_name='上级评论',
        related_name='%(class)s_child_comments',
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )
    reply_to = models.ForeignKey(
        'self',
        verbose_name='回复给',
        related_name='%(class)s_rep_comments',
        blank=True,
        null=True,
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ['id']
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def __str__(self):
        return self.body

    def count(self):
        return len(Comment.objects.all())

comments/forms.py
from .models import Comment
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class CommentForm(forms.ModelForm):
    parent_comment_id = forms.IntegerField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Comment
        fields = ['body']

comments/views.py
from blog.models import Article
from .models import Comment
from .forms import CommentForm
from django.views import generic


class CommentPostView(generic.FormView):
    form_class = CommentForm
    template_name = 'comments/reply.html'
    success_url = ''

    def form_valid(self, form):
        user = self.request.user
        article_id = self.kwargs['article_id']
        article = Article.objects.get(pk=article_id)
        comment = form.save(commit=False)
        comment.article = article
        comment.author = user
        parent_comment_id = self.kwargs.get('parent_comment_id')
        if parent_comment_id:
            parent_comment = Comment.objects.get(pk=parent_comment_id)
            comment.parent_comment = parent_comment
            if parent_comment.parent_comment:
                comment.parent_comment = Comment.objects.get(pk=parent_comment.parent_comment.pk)
            comment.reply_to = parent_comment

        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        article_id = self.kwargs['article_id']
        if article_id:
            self.success_url = f'/blog/article/{article_id}'
        return str(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article_id = self.kwargs['article_id']
        parent_comment_id = self.kwargs['parent_comment_id']
        context['article_id'] = article_id
        context['parent_comment_id'] = parent_comment_id
        context['comment_form'] = CommentForm
        return context

templates/comments/comment_list.html
{% load comments_tags %}
{% load account_tags %}
{% load static %}


<h5>共有{{ comments.count }}条评论</h5>
{% if comments %}


    {% child_comments comments comment=None as parent_comments %}
    {% for comment in parent_comments %}
    <div class="row">
        <div class="{% if comment.reply_to %} offset-1 col-11 {% else %} col-12 {% endif %}">
            <hr>
            <p>
                <img
                    class="img-rounded profile-thumbnail pull-left"
                    style="margin: 0 2px 0 0"
                    src="{{ comment.author|gravatar:'20' }}"
                >

                <cite>
                    {{ comment.author }}
                </cite>

                {% if comment.reply_to %}
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-arrow-right" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" d="M10.146 4.646a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L12.793 8l-2.647-2.646a.5.5 0 0 1 0-.708z"/>
                      <path fill-rule="evenodd" d="M2 8a.5.5 0 0 1 .5-.5H13a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 8z"/>
                    </svg>
                    <img class="img-rounded profile-thumbnail pull-left" style="margin: 0 2px 0 0" src="{{ comment.reply_to.author|gravatar:'20' }}">
                <cite>{{ comment.reply_to.author }}</cite>
                {% endif %}

            </p>
            <div>{{ comment.body|safe }}</div>

            <div>
                <span style="color: gray">
                    {{ comment.create_time|date:"Y-m-d H:i" }}
                </span>

                <!-- 加载 modal 的按钮 -->
                {% if user.is_authenticated %}
                <button type="button" class="btn btn-light btn-sm text-muted" onclick="load_modal({{ article.id }}, {{ comment.id }})">
                    回复
                </button>
                {% else %}
                <a class="btn btn-light btn-sm text-muted" href="{% url 'account:login' %}">回复</a>
                {% endif %}
            </div>

            <!-- Modal -->
            <div class="modal fade"
                 id="comment_{{ comment.id }}"
                 tabindex="-1"
                 role="dialog"
                 aria-labelledby="CommentModalCenter"
                 aria-hidden="true">

                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                    <div class="modal-content" style="height: 480px">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.author }}：</h5>
                        </div>
                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                    </div>

                </div>
            </div>

        </div>
    </div>

    {% endfor %}


<script src="{% static 'blog/js/blog.js' %}"></script>
{% endif %}

templates/comments/post_comment.html
{% if user.is_authenticated %}
    <div>
        <form action="{% url 'comments:post_comment' article.id %}" method="POST">
            {% csrf_token %}

            <div class="form-group">
                <label for="body" hidden></label>
                {{ comment_form.media }}
                {{ comment_form.body }}
            </div>

            <!-- 提交按钮 -->
            <button type="submit" class="btn btn-primary ">提交评论</button>

        </form>
    </div>
    <br>
{% else %}
    <br>
    <h5 class="row justify-content-center">
        请<a href="{% url 'account:login' %}">登录</a>后回复
    </h5>
    <br>
{% endif %}

templates/comments/reply.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>
    <form action="." method="POST" id="reply_form">
        {% csrf_token %}
        <div class="form-group">
            <div id="test">
                <label for="body" hidden></label>
                {{ comment_form.media }}
                {{ comment_form.body }}
            </div>
        </div>
    </form>
    <!-- 提交按钮 -->
    <button onclick="confirm_submit({{ article_id }}, {{ parent_comment_id }})" class="btn btn-primary">发送</button>

    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js">
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


    <!-- csrf token -->
    <script src="{% static 'blog/js/csrf.js' %}"></script>

    <script>
    $(function(){
        $(".django-ckeditor-widget").removeAttr('style');
    });

    function confirm_submit(article_id, comment_id){

        let content = CKEDITOR.instances['id_body'].getData();

        $.ajax({
            url: '/comments/post-comment/' + article_id + '/' + comment_id,
            type: 'POST',
            data: {body: content},

            success: function(e){
                if(e === '200 OK' || '302 FOUND'){
                    parent.location.reload();
                }
            }
        });
    }
    </script>

</body>
</html>